### ISSUE TITLE
Transitive clojure 1.2.1 dependencies

### ISSUE THREAD

**Issue by trptcolin** [dakrone/clojuredocs-client#6]
Apologies in advance: this falls into the "I'm not really sure what should change" category for me. Looks like the clj-http and cheshire versions pointed at by project.clj on master end up bringing in clojure 1.2.1 somehow. I'm not entirely sure how this is possible, since I wasn't seeing those jarfiles go into lib/ or lib/dev/ when using cd-client from reply, but it was breaking compilation on Travis CI, and I was able to reproduce locally (but only after blowing away my whole ~/.m2 directory)... weird.

For now, I'm just adding org.clojure/clojure to the exclusions list, and that does the trick. Maybe it's just the person doing AOT's responsibility to exclude everything they need to, and I'm overthinking this...

**Comment by devn** [comment]
Could you say a bit more about the issue?

Might it be a lein-multi issue? I notice cheshire builds against 1.2.0 and 1.3.0-RC0, for instance.

**Comment by trptcolin** [comment]
I probably need to do some more investigation, but whatever it is only surfaces when doing AOT compilation (via lein compile). This was in https://github.com/trptcolin/reply

I don't know much about lein-multi.

The build attempt is here: http://travis-ci.org/#!/trptcolin/reply/builds/570838  Had a bit of help tracking this down here:  http://travis-ci.org/#!/trptcolin/reply/builds/570838 The really weird thing to me was that I didn't see extra clojure jars. 

I'd be interested to hear whether others can reproduce - I haven't done much AOT compiling before, so maybe it's a well-known thing?

**Comment by dakrone** [comment]
Strange, I'm not seeing Clojure 1.2.1 brought in at all with the master branch of reply. Here's what I'm seeing for a dep-tree:

```
Before (with exclusions):
[INFO] --- maven-dependency-plugin:2.1:tree (default-cli) @ reply ---
[INFO] reply:reply:jar:0.1.0-SNAPSHOT
[INFO] +- midje:midje:jar:1.3-alpha4:test
[INFO] |  +- org.clojure:math.combinatorics:jar:0.0.1:test
[INFO] |  +- org.clojure:algo.monads:jar:0.1.0:test
[INFO] |  |  \- org.clojure:tools.macro:jar:0.1.0:test
[INFO] |  \- org.clojure:core.unify:jar:0.5.1:test
[INFO] +- lein-midje:lein-midje:jar:1.0.7:test
[INFO] +- org.clojure:clojure:jar:1.3.0:compile
[INFO] +- org.clojars.trptcolin:jline:jar:2.6-SNAPSHOT:compile
[INFO] |  \- org.fusesource.jansi:jansi:jar:1.7:compile
[INFO] +- org.thnetos:cd-client:jar:0.3.1:compile
[INFO] |  +- clj-http:clj-http:jar:0.2.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.1.2:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.1.2:compile
[INFO] |  |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.5:compile
[INFO] |  |  \- commons-io:commons-io:jar:1.4:compile
[INFO] |  \- cheshire:cheshire:jar:2.0.2:compile
[INFO] |     +- org.codehaus.jackson:jackson-core-asl:jar:1.8.5:compile
[INFO] |     \- org.codehaus.jackson:jackson-smile:jar:1.8.5:compile
[INFO] +- clj-stacktrace:clj-stacktrace:jar:0.2.4:compile
[INFO] \- clojure-complete:clojure-complete:jar:0.1.4:compile


After (without exclusions):
[INFO] --- maven-dependency-plugin:2.1:tree (default-cli) @ reply ---
[INFO] reply:reply:jar:0.1.0-SNAPSHOT
[INFO] +- midje:midje:jar:1.3-alpha4:test
[INFO] |  +- org.clojure:math.combinatorics:jar:0.0.1:test
[INFO] |  +- org.clojure:algo.monads:jar:0.1.0:test
[INFO] |  |  \- org.clojure:tools.macro:jar:0.1.0:test
[INFO] |  \- org.clojure:core.unify:jar:0.5.1:test
[INFO] +- lein-midje:lein-midje:jar:1.0.7:test
[INFO] +- org.clojure:clojure:jar:1.3.0:compile
[INFO] +- org.clojars.trptcolin:jline:jar:2.6-SNAPSHOT:compile
[INFO] |  \- org.fusesource.jansi:jansi:jar:1.7:compile
[INFO] +- org.thnetos:cd-client:jar:0.3.1:compile
[INFO] |  +- clj-http:clj-http:jar:0.2.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.1.2:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.1.2:compile
[INFO] |  |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.5:compile
[INFO] |  |  \- commons-io:commons-io:jar:1.4:compile
[INFO] |  \- cheshire:cheshire:jar:2.0.2:compile
[INFO] |     +- org.codehaus.jackson:jackson-core-asl:jar:1.8.5:compile
[INFO] |     \- org.codehaus.jackson:jackson-smile:jar:1.8.5:compile
[INFO] +- clj-stacktrace:clj-stacktrace:jar:0.2.4:compile
[INFO] \- clojure-complete:clojure-complete:jar:0.1.4:compile
```

Can you have the Travis build run: `lein pom && mvn dependency:tree` and see what that says? That should tell who is the culprit for the 1.2.1 version.

**Comment by trptcolin** [comment]
Right, so the deal is: reply's master branch now adds exclusions for org.clojure/clojure, just to work around this. That works great for me, but I opened this ticket in case others saw the same thing. 

Here's something else weird: checking out to cee9a4618235e1419e227f75b4306fd6f55935a2 on reply and running `lein pom && mvn dependency:tree` doesn't show any other clojure versions, which matches what I'm seeing in my lib and lib/dev directories, but `lein compile` still fails:

```
Caused by: java.lang.NoSuchMethodError: clojure.lang.KeywordLookupSite.<init>(ILclojure/lang/Keyword;)V
    at leiningen.util.paths$native_arch_path.<clinit>(paths.clj:32)
    at leiningen.util.paths__init.load(Unknown Source)
    at leiningen.util.paths__init.<clinit>(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
```

I haven't been paying much attention to Leiningen issues; I'm starting to think maybe this belongs there? Seems silly for every project to have to worry about what other projects might want to use it and potentially AOT compile things.

**Comment by trptcolin** [comment]
OK, I'm pretty convinced at this point, based on [this lein issue](https://github.com/technomancy/leiningen/issues/375), so I'm going to close this issue. Sorry for the goose chase!
